import { addCollection } from '@iconify/react';
import skillIconCollection from './solar-icons.json';

// Registered once, offline, for every page that renders a solar icon (skill
// cards, skill timeline, flow-stage rows): skillIconCollection (generated by
// scripts/generate-skill-icons.ts) already contains every base name any of
// them requests, so the Icon component never falls back to a network call
// against Iconify's public API. Module bodies run once regardless of how
// many call sites import this, so every importer just needs `import
// './register-solar-icons'` (or `'../data/register-solar-icons'`) for the
// side effect - no function call needed.
addCollection(skillIconCollection);
