import React, { type ReactNode } from 'react';
import Link from '@docusaurus/Link';
import useBaseUrl from '@docusaurus/useBaseUrl';
import { Icon, addCollection } from '@iconify/react';
import skillIconCollection from '../../data/solar-icons.json';
import { SKILL_ICON_NAMES } from '../../data/skill-icons';
import type { OriginalSkillCardProps } from './types';
import styles from './original-skill-card.module.css';

// Registered once, offline: every icon this card can ever request is
// already in skillIconCollection (generated by scripts/generate-skill-
// icons.ts), so the Icon component below never falls back to a network
// call against Iconify's public API.
addCollection(skillIconCollection);

/**
 * The landing-page summary card for an AlexRebula-original skill, matching
 * AnalyticsWidgetSummary from rm/presentation/alexrebula/src/sections/
 * overview/analytics/analytics-widget-summary.tsx: the same green gradient,
 * background shape illustration, and typography, with the trend indicator
 * and sparkline chart removed (there's no numeric metric to show here) and
 * a semantically-matched icon in place of the dashboard's glass illustration.
 */
export function OriginalSkillCard({ category, name }: OriginalSkillCardProps): ReactNode {
  const shapeUrl = useBaseUrl('/img/shape-square.svg');
  const iconBase = SKILL_ICON_NAMES[`${category}/${name}`];

  return (
    <Link to={`/${category}/${name}`} className={styles.card}>
      <span className={styles.iconBox}>
        <Icon icon={`solar:${iconBase}-bold-duotone`} width={30} height={30} />
      </span>
      <span className={styles.label}>AlexRebula Original.</span>
      <span className={styles.name}>/{name}</span>
      <span
        className={styles.shape}
        style={{ WebkitMaskImage: `url(${shapeUrl})`, maskImage: `url(${shapeUrl})` }}
        aria-hidden="true"
      />
    </Link>
  );
}
