import React, { type ReactNode } from 'react';
import { Icon, addCollection } from '@iconify/react';
import skillIconCollection from '../../data/solar-icons.json';
import { SKILL_ICON_NAMES } from '../../data/skill-icons';
import type { SkillIconProps } from './types';

// Registered once, offline: every icon this can ever request is already in
// skillIconCollection (generated by scripts/generate-skill-icons.ts), so the
// Icon component below never falls back to a network call against Iconify's
// public API.
addCollection(skillIconCollection);

/**
 * A skill's solar icon, looked up from `SKILL_ICON_NAMES` by "category/name".
 * Shared between `SkillCard` (the landing page's per-skill summary card) and
 * `SkillTimeline` (issue #157's dogfooding of giselle-mui's Timeline, which
 * needs the same icon in each phase's dot). The icon registration used to
 * live only in `SkillCard`, promoted here once a second real caller existed.
 */
export function SkillIcon({ category, name, size = 30 }: SkillIconProps): ReactNode {
  const iconBase = SKILL_ICON_NAMES[`${category}/${name}`];
  return <Icon icon={`solar:${iconBase}-bold-duotone`} width={size} height={size} />;
}
