import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Autogenerated from the docs/ folder structure (configured via the docs
// plugin's `path: '../docs'`). Category folders get their labels/order from
// their own `_category_.json` files. Only categories that contain at least
// one page render — new pages from future content tickets show up here with
// no sidebar edits needed.
const sidebars: SidebarsConfig = {
  skillsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
