import React, { type ReactNode } from 'react';
import Link from '@docusaurus/Link';
import useBaseUrl from '@docusaurus/useBaseUrl';
import clsx from 'clsx';
import { Icon, addCollection } from '@iconify/react';
import skillIconCollection from '../../data/solar-icons.json';
import { SKILL_ICON_NAMES } from '../../data/skill-icons';
import type { SkillCardProps } from './types';
import styles from './skill-card.module.css';

// Registered once, offline: every icon this card can ever request is
// already in skillIconCollection (generated by scripts/generate-skill-
// icons.ts), so the Icon component below never falls back to a network
// call against Iconify's public API.
addCollection(skillIconCollection);

/**
 * The landing-page summary card for a skill with no live upstream
 * counterpart: "original" (never existed upstream) and "inherited" (existed
 * upstream once, since removed there) both render through this, each with
 * their own color/icon/label. Visual shape is hand-ported into this site's
 * plain CSS Modules from giselle-mui's stat-card design (a MUI component
 * this site otherwise has no dependency on), not its literal implementation:
 * the same gradient card, background shape illustration, and typography,
 * with the trend indicator and sparkline chart removed (there's no numeric
 * metric to show here) and a semantically-matched icon in their place.
 */
export function SkillCard({ category, name, color, label }: SkillCardProps): ReactNode {
  const shapeUrl = useBaseUrl('/img/shape-square.svg');
  const iconBase = SKILL_ICON_NAMES[`${category}/${name}`];

  return (
    <Link to={`/${category}/${name}`} className={clsx(styles.card, styles[color])}>
      <span className={styles.iconBox}>
        <Icon icon={`solar:${iconBase}-bold-duotone`} width={30} height={30} />
      </span>
      <span className={styles.label}>{label}</span>
      <span className={styles.name}>/{name}</span>
      <span
        className={styles.shape}
        style={{ WebkitMaskImage: `url(${shapeUrl})`, maskImage: `url(${shapeUrl})` }}
        aria-hidden="true"
      />
    </Link>
  );
}
